### ISSUE TITLE
Eliminate need to explicitly set array lengths

### ISSUE THREAD

**Issue by adeschamps** [adeschamps/lcm#3]
LCM messages include the length of an array as a separate field that must be set explicitly. This is a very C-ish thing to do, and I think the Rust api should take care of it for you.

**Comment by adeschamps** [comment]
An easier option would be to check that the length fields agree during the encode function, and fail to encode if they don't agree.

**Comment by neachdainn** [comment]
I'm not sure what the proper Github protocol is, but I am starting to work on this issue.

**Comment by adeschamps** [comment]
I'm not sure either, but since there aren't that many people working on this repo, I don't think we'll run into too many issues.

Thanks!
